---
title: "Project Ideas and Notes"
author: "Eric Escobar-Chena and Emilio M. Bruna"
date: "updated: `r Sys.Date()`"
mainfont: SourceSansPro
geometry: margin=1in
fontsize: 12pt
linkcolor: darkmidnightblue
urlcolor: darkmidnightblue
header-includes:
- \usepackage{fancyhdr}
- \pagestyle{fancy}
# - \fancyfoot[R]{last update `r Sys.Date()`}
- \fancyfoot[C]{ }
- \fancyhead[R]{p. \thepage}
- \fancyhead[L]{last update `r Sys.Date()`}
- \usepackage[default]{sourcesanspro}
# - \usepackage{parskip}
# - \usepackage{xcolor}
- \AtBeginDocument{\let\maketitle\relax}
# - \usepackage{sectsty} \sectionfont{\centering}
# - \usepackage{titlesec}
# - \usepackage{sectsty} \sectionfont{\centering\color{darkmidnightblue}}
# - \usepackage{sectsty} \subsectionfont{\color{darkmidnightblue}}
# - \titlespacing{\section}{0pt}{12pt plus 2pt minus 1pt}{0pt plus 1pt minus 1pt}
# - \titlespacing{\subsection}{0pt}{12pt plus 2pt minus 1pt}{0pt plus 1pt minus 1pt}
# - \titlespacing{\subsubsection}{0pt}{12pt plus 2pt minus 1pt}{0pt plus 1pt minus 1pt}
# - \definecolor{darkcerulean}{rgb}{0.03, 0.27, 0.49}
- \definecolor{darkmidnightblue}{rgb}{0.0, 0.2, 0.4}
bibliography: "eric-thesis.bib"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(knitr)
library(citr)
```

### *Notes from conversation with Julian:*

1.  Low-hanging fruit: Effect of connectivity on (a) species and functional group diversity and abundance
2.  Next level: Movement & Dispersal. There are large areas of forest where it is possible to capture beetles for Mark-Release-Recapture (MRR) experiments.
3.  Higher-risk, Higher reward (even if they don't go in MS, can be set-up for potential PHD projects): Experiments on Ecosystem Services

-   dung burial, decomposition, soil properties based on results of 1 & 2 (buckets with dung and beetle assemblages)
-   gas (e.g., methane) emissions
-   seed dispersal/burial/germination

### Example studies

1.  Diversity and Abundance

-   @WOS:000178929600002: "56% of individuals were captured in the continuous forest, 29% in the mosaic habitat and 15% in the forest fragments"

2.  Movement & Dispersal

3.  Ecosystem Services

# Other stuff to work on:

1.  Species List & Keys for Dung Beetles of the Southeastern US
2.  Any previous work done on dung beetles in Southeastern US
3.  List of Equipment and Tools needed

-   Dung beetle traps
-   alcohol
-   bait

# Species

\newpage

# INTRODUCTION

<!-- Good stuff in here: -->

<!-- https://link.springer.com/article/10.1007/s10531-017-1299-7 -->

<!-- https://www.sciencedirect.com/science/article/pii/S1470160X19303486 -->

1.  Paragraph 1: In an increasingly fragmented world, corridors are thought to be an important strategy of connecting isolated patches to promote population persistence and increase diversity in connected patches. This can ultimately have consequences for ecosystem processes in fragments.

2. Paragraph 2: Despite this, direct evidence of movement between patches is limited. Plenty of studies have demonstrated that the diversity or abundance of organisms is similar in corridors and the primary habitat to which they are connected. However, studies demonstrating animals actually move from one patch through a corridor to another patch are surprisingly rare (but see examples).  NB: might have to say "although there is ample evidence that vertbrates move through corridors, studies documenting the movements of invertebrates - the dominant species on earth - are limited".

3. Paragraph 3: Part of the challenge in assessing the  efficacy of corridors is the confounding effects of patch area and the length of habitat edges (see resasco 2014 etc); to address this it is necessary to compare connected and unconnected areas of equal area and shape.

4. Paragraph 4: Dung beetles have emerged as a model system with which to test hypotheses on how anthropogenic landscape alterations influence biodiversity. They are locally species rich, exhibit variety in key funcitonal traits (size, foraging style,,....), and they provide critical ecosystem services. robust (but not *too* robust): studies have shown diversity of dung beetles can be lower in fragments, but that they can be found in corridors and are capable of dispersing for up to 1 km. 

5. Paragraph 5: I am proposing to use a landscape-scale fragmentation experiment to test the effects of corridors on the diversity and dispersal dung beetles and the ecosystem services they provide. Specifically, I will test the following predictions:

1. Diversity will be higher in connected patches. To test this prediction, I will sample dung beetles with pitfall traps and use non-parametric estimators of species diversity

2. Dung beetles disperse through corridors, with larger beetles dispersing more quickly (size-dependent dispersal ability)

3. Dung removal rates will be highest in connected patches.   

To test there predictions, I will use a combination of passive sampling and a MRR experiment and control for the confounding effects of edge and area.  


# Methods


Prediction 1: Pitfall trapping (arrangement, timing)

Prediction 2: MRR experiment, where will recapture traps be placed?

Prediction 3: experimental design poop disappearance



\newpage

## What is predicted about how corridors influence the diversity of insects communities (with an emphasis on Dung Beetles) in patches?

Are corridors predicted to enhance diversity in connected patches? What is the mechanism\>? A certain species groups are predicted to drive this change in diversity - rare species, larger species, specialists, particular function groups, better fliers, etc.? (*Note: "Corridors" = Riparian strips, living fences, linear fragments, etc.*)

-   **Prediction 1:** Diversity higher in connected patches (citations in Damschen et al PNAS, others)

-   **Prediction 2:** Diversity could be lower in patches (in specific case of corridor project, only getting open space species)

### Empiricial Results

### 1. Studies that have compared diversity of Dung Beetles in Corridors and Other Habitats (e.g., primary forest, pastures) have found that:

-   **Diversity increases:** [@WOS:000399235300014; @WOS:A1995TL67200023]

-   **Diversity decreases:**

-   **Similar diversity in both:**

### 2. Studies that have actually compared the diversity of patches that are connected by a corridor vs. patches that are unconnected

-   **Diversity increases:**

-   **Diversity decreases:**

-   **Similar diversity in both:**

## What is predicted or known about insect movement through corridors (with an emphasis on Dung Beetles)?

Do Corridors facilitate movement between patches? Are particular species or groups more able to move through corridors than others - larger species, specialists on particular resources, particular functional groups, better fliers, etc.?

### 1. Studies that have assessed movement of Dung Beetles have found the following can play an important role:

-   **Habitat Preference:** [@WOS:000360850000002, @WOS:000262759300008].

-   **Wing Loading:** [@WOS:000360850000002]

-   **Sex:**

-   **Foraging Mode:**

-   **Size:**

-   **Invasive vs. Native:**

-   **No inter-specific or inter-group differences in movement:**

### 2. Studies that have estimated dispersal distance:

\newpage

# THE QUESTIONS

Question 1: Is dung beetle abundance greater in connected patches than isolated ones?

<!-- Review predictions (or results) from studies of habitat fragments, other corridor studies, etc to refine this prediction -->

Question 2: Is dung beetle diversity greater in connected patches than isolated ones?

> Prediction: Species diversity is greater in connected patches than isolated ones (due to the greater representation of rare species) OR Prediction: Diversity of \_\_\_\_\_\_\_ (e.g., specialists, foraging strategy X, etc.) is greater in connected patches, but the Diversity of \_\_\_\_\_\_\_\_ (e.g., generalists, foraging strategy Y) will be the similar in both. OR The diversity is similar, but the community composition changes to one dominated by specialists instead of generalists

2.  Do Dunge beetles move through corridors?



References


